### ISSUE TITLE
Tag Latest Changes

### ISSUE THREAD

**Issue by EmilyMatt** [rustls/tokio-rustls#11]
In commit b5b7c0e webpki was updated, which resolved a vulnerability*, but this change hasn't been tagged yet, which prevents other crates from overcoming this issue(tokio-tungstenite for instance).
When can a new tag be expected for this crate?
Thanks :)

* https://rustsec.org/advisories/RUSTSEC-2023-0053

**Comment by djc** [comment]
No bump is needed, since the version bump is semver-compatible it should propagate to downstream libraries/applications automatically.
