### ISSUE TITLE
Triggering renegotiation

### ISSUE THREAD

**Issue by manglemix** [rustls/tokio-rustls#16]
I plan to use tokio_rustls for some long running task that should never shut down. Specifically there is one persistent connection from the client to the server, so technically speaking the session key will be the same the entire time and I will lose forward secrecy. I've seen some clues that maybe rustls has renegotiation built in, so I was wondering if there is a way to trigger it through this crate.

**Comment by djc** [comment]
What you're calling renegotation is intentionally not supported in rustls:

https://docs.rs/rustls/latest/rustls/manual/_02_tls_vulnerabilities/index.html#renegotiation

However, rustls will enforce [limits](https://github.com/rustls/rustls/blob/main/rustls/src/record_layer.rs#L8) to make sure that a given connection doesn't run into the situation of losing forward secrecy. Additionally, there is passive support for key updates, so if the peer requests a key update we will update our keys (and reset the limit).

**Comment by manglemix** [comment]
I see. I must've made a mistake. Thank you anyway

**Comment by djc** [comment]
In general, if rustls would allow your connection to get into a mode where forward secrecy is (statistically) compromised, we'd definitely consider that a security vulnerability. So you may assume that rustls takes care of these risks for you, and you don't have to do anything extra to avoid them.
