### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by crawford** [rustls/tokio-rustls#19]
It would be really convenient if this repository had the tags corresponding to each release on crates.io since it's a lot easier to read source code here. Is it feasible to push the tags?

**Comment by djc** [comment]
We'd first have to recover which commits the releases were made from. That's a bit of work and not that high of a priority for me as a volunteer maintainer. If you want to list dig up some versions and corresponding commits, I'd be happy to push tags for them.

**Comment by crawford** [comment]
Thanks @djc, I'd be happy to pull together a list. Give me a couple days to script something up.

**Comment by djc** [comment]
@crawford do you think you will be able to do some work for this?

**Comment by crawford** [comment]
Sorry, I haven't had a chance to revisit this. I imagine this is going to require a bit of a "fuzzy" solution, since the crates go through a transformation before they end up on crates.io, so it will likely take some trial and error. I do still intend on writing such a tool, but I don't have a timeline for you, unfortunately. Feel free to close this issue, since I know these lingering "issues" can be taxing.

**Comment by mbrubeck** [comment]
Here are all the versions where the git commit is recorded in the `.crate` package’s `.cargo_vcs_info.json` file:

0.8.0-alpha: e7231821086ed7d1c3525e9455624f146450713c
0.8.0: f6e8f86382330143b3fdc8d82eac1eba09616db6
0.8.1: d72eb459b2de777f07da65fcdbbe293bb54a6b3b
0.9.0: db21c4c94751be3a5040af1eea9c58641dc37bda
0.10.0-alpha: 8b8647b43d79522b308532b27987349730388c92
0.9.1: 08340df78f022653bbf0e359d623da3af967167e
0.10.0-alpha.1: d8ab52db551e4d4080b73cf3e338e9f07d265fdd
0.9.2: 3b8ce1706d9fa4ace78ecf2d753674b322b97986
0.10.0-alpha.2: b6e39450ce48d4b19c0095952df867e31fe5a51d
0.9.3: fe8fafecee85191efb73aa7edaed7021a5c8beff
0.10.0-alpha.3: 14846cab2bba1aff351599b0e83dbbc0607d2a07
0.10.0-alpha.4: 67fa9a66336789c71691d6c28a99e6146bb02d4a
0.10.0: f13aa17d10b36b901e5f688aa05b7b973907058a
0.12.0-alpha.1: 0fceadf79919723564ef9033bb6b502fec28d8c1
0.12.0-alpha.2: 0386abcee1036f9ae18a7d50226a223c74a21eab
0.10.1: f59c06c71cb200cc0755090128da5dff5ca387e6
0.9.4: 61d005fb74f54cb575171f383baebabaa8cf6282
0.10.2: 3ceb04c0a04e8ec7e8de78aad6c7b2da2b26e7cd
0.12.0-alpha.3: aa6e8444def3b4aa62099583459fbdf73e4f2e38
0.12.0-alpha.4: 64948af0a79e6e8baef5e025c59ca5cdd59d9351
0.12.0-alpha.5: 9f6d3c74bf954af0dc79b78e2d4adf0bb27ab347
0.12.0-alpha.6: ff3d0a4de3f0493b9c108baf9555c2108f406f22
0.12.0-alpha.7: fe113dc6b00012f82b98370cc57aa7bbd71e384c
0.12.0-alpha.8: 314625390756e6ff73af9d984913b49b54d1a92e
0.12.0: d42540f52f405555c278ecf65063f9a8fb93cd48
0.12.1: 7530e2f7396d4c5d72be5693281338a78566380d
0.10.3: 261d6f38b283fe44a64681f1c958e17f2c183ac1
0.12.2: d7862fae8ae6870ad27bd62b7960798825998a62
0.13.0: a2d9ebb0d897baba3e8ada49d6a3f39ee26d526c
0.13.1: 3be701cefb573341db74254f137a4d54aefa44ce
0.12.3: ddee62100913760e7a2728cc8d9b3c22f3f1f562
0.14.0: c2dd82e32355c69ae41d83ad92f865ee18e31ca9
0.14.1: e8a8a599713e044525d133264665091130598b05
0.20.0: e6ef54641b911cfcf23b77a8c4826ae0f8e9870e
0.21.0: 0c2d573a4ec77ef253fc040eea077f620dd5f56e
0.15.0: 58ba03d17ea707b2589a303d773b8e9617e2b631
0.21.1: 5ea7060a4568b01ce3534dc58b7cf1436cbef0c6
0.22.0: f85882fbc7c0f5e5aafbe3f8637ec333be7ecd68
0.23.0: 48caaf751fa68907da9eb3b4e0980f3076316ac7
0.23.1: 8519354ad6681e5ef53da7d37edde4706ccfc76f
0.23.2: 47b2ef50c1f99017362625f6da26295e340c758d
0.23.3: bcf4f8e3f96983dbb7a61808b0f1fcd04fb678ae
0.23.4: 0cf2ccc1ad183a83f234271877ff450c20908cce
0.24.0: 7ea7a17831691e8b0a9cfae3132d2d2f0f64221c
0.24.1: 15020d31e50ada3995f0842434f60dc9243a9c76
0.25.0-alpha.1: dc0ddb6bfa563bc032c34d5c6f43265affd2437b
0.25.0-alpha.2: 82d32c410f2364332c5df656717193f278769e1c
0.25.0-alpha.3: f3e1925ffc5d0f74172f738d0f6df1c8be9b73b7
0.25.0-alpha.4: 8212ca4b1e2e3a3ba1bf6e03364ada74a48159d8
0.25.0: 534344388ecc6634a133bd619c49170a79e38dc8

Note, some of the commits listed are not present in this repository.

**Comment by djc** [comment]
@mbrubeck thanks! I've pushed tags for 0.20.0 and later (non-pre) releases.

**Comment by djc** [comment]
@mbrubeck I've added tags for them.
