### ISSUE TITLE
tokio-rustls write only first IoSlice when use write_vectored 

### ISSUE THREAD

**Issue by incker** [rustls/tokio-rustls#24]
Looks like `is_write_vectored` returns true 

But function `write_vectored` does not work correct. I receive only first slice when I read stream

I am sorry I have not code example to reproduce

**Comment by thomaseizinger** [comment]
> Looks like `is_write_vectored` returns true

Where do you see that? For both `client::TlsStream` and `server::TlsStream`, it is not overridden which means it will return `false`:

- https://docs.rs/tokio-rustls/latest/src/tokio_rustls/client.rs.html#134-244
- https://docs.rs/tokio-rustls/latest/src/tokio_rustls/server.rs.html#94-129
