### ISSUE TITLE
Override `poll_write_vectored`?

### ISSUE THREAD

**Issue by thomaseizinger** [rustls/tokio-rustls#26]
At present, `poll_write_vectored` is not overridden:

- https://docs.rs/tokio-rustls/latest/src/tokio_rustls/client.rs.html#134-244
- https://docs.rs/tokio-rustls/latest/src/tokio_rustls/server.rs.html#94-129
- https://docs.rs/tokio-rustls/latest/src/tokio_rustls/lib.rs.html#522-553
- https://github.com/rustls/tokio-rustls/blob/6df177a7515d9fb2d3e8ba900ba833c5830b4136/src/common/mod.rs#L290-L324

I think it would make sense to do so though. At the moment, the implementation of `poll_write` will perform IO as soon as the buffer is written (which makes sense). However, if the application would have more data to send that sits in different buffers, performing IO after every `poll_write` might lead to multiple TCP packets being sent.

The only way around this (I think?) would be to re-design the upper layer to be able to provide a single byte buffer. That is not always feasible and/or desirable. Additionally, that is exactly what `poll_write_vectored` is for. A proper implementation of would send all packets down to the rustls session and only perform IO once that buffer is either full or we've written all buffers passed to us.

I've created a basic draft in https://github.com/rustls/tokio-rustls/pull/25.

**Comment by quininer** [comment]
I agree with impl `write_vectored` as the optimization over current situation.

Currently, rustls does not provide backpressure https://github.com/rustls/rustls/blob/v/0.21.8/rustls/src/conn.rs#L232 . If we want to impl buffer write without rustls support, we can treat rustls writer as an infinite buffer and set a reasonable buffer length ourselves.

But this is a huge behavior change. and if rustls hopes to provide a write-through API in future, it would be reasonable to keep current behavior. https://github.com/tokio-rs/tls/issues/136#issuecomment-1558899102

cc @djc

**Comment by thomaseizinger** [comment]
I don't think I am following you there. Isn't that orthogonal to vectored writes? For `poll_write_vectored` to make sense, I think we simply need to first write all buffers and then ask the session `wants_write`.

The docs for `poll_write_vectored` state that it needs to behave as if `poll_write` was called with a concatenated buffer. How is internal buffering in rustls related to that?

**Comment by quininer** [comment]
Yes, they are orthogonal. the buffer writer is just a related discussion of this line.

> A proper implementation of would send all packets down to the rustls session and only perform IO once that buffer is either full or we've written all buffers passed to us.

**Comment by djc** [comment]
The write-through API is currently being worked on. https://github.com/rustls/rustls/pull/1420

**Comment by paolobarbolini** [comment]
With https://github.com/rustls/rustls/pull/1640 this could make sense to have. I may find some time to look into it.
