### ISSUE TITLE
Allow non-static lifetime for ServerName?

### ISSUE THREAD

**Issue by sunng87** [rustls/tokio-rustls#35]
The new release requires `'static` for `ServerName` in `TlsConnector`, which means I need to specify it from a `&'static str`. However, in my application, the server name is given by user configuration and there is no guarantee for it being `'static`.

https://github.com/sunng87/rustmann/pull/37/files#diff-f229bc4b874c8edcd2c19a11fe9871e47d51519cf51ed829058f0bdbb1e4b27bR21

Any chance to provide custom lifetime for `ServerName`?

**Comment by sunng87** [comment]
That works for me. Thank you!

We can use `.to_owned()` to convert `ServerName` to `'static`, which as @djc mentioned, requires `alloc` for rustls-pki-types

**Comment by cpu** [comment]
That's also approximately [what happened under the hood](https://github.com/rustls/rustls/blob/bbd9abca106c68ab01c385a1bb7399be46cee9c0/rustls/src/client/client_conn.rs#L384C4-L385) prior to the pki-types switch.
