### ISSUE TITLE
How to get peer certificates as server?

### ISSUE THREAD

**Issue by moparisthebest** [rustls/tokio-rustls#39]
I currently accept the connection with [TlsAcceptor.accept](https://docs.rs/tokio-rustls/latest/tokio_rustls/struct.TlsAcceptor.html#method.accept) and then call get_ref() which gets me a reference to [ServerConnection](https://docs.rs/rustls/0.22.0/rustls/server/struct.ServerConnection.html) which has everything I need on it, the problem is this can return None for peer_certificates/sni/alpn until the handshake is finished, and provides [complete_io()](https://docs.rs/rustls/0.22.0/rustls/server/struct.ServerConnection.html#method.complete_io) to finish the handshake, but that's not async, is there an async version of this or should this be done another way?

I need to validate the client certificate before I do any IO on it, and don't see another way to guarantee the handshake is complete.

**Comment by djc** [comment]
Once the `Accept` future yielded by `TlsAcceptor::accept()` yields the `TlsStream`, you should be able to access the `rustls::ServerConnection` via `get_ref()`. At this point the handshake has completed (per the documentation of the `Accept` future).

**Comment by moparisthebest** [comment]
:facepalm: indeed, no idea how I missed that, thanks much!
