### ISSUE TITLE
Secure WebSocket Implementation with tokio-tungstenite | tokio-rustls | rustls-platform-verifier

### ISSUE THREAD

**Issue by Tahinli** [rustls/tokio-rustls#65]
Hi, I'm trying to build wss connection with these crates, but I really have problem, I can't implement this properly.
Details:
https://users.rust-lang.org/t/tokio-tungstenite-rustls-implementation/110211

**Comment by djc** [comment]
You posted the thread on the users forum 1 hour ago. Please give it more time before pinging our issue tracker again -- this isn't really a support forum.

**Comment by Tahinli** [comment]
> You posted the thread on the users forum 1 hour ago. Please give it more time before pinging our issue tracker again -- this isn't really a support forum.

I really don't like to make people busy, but you know I couldn't fix it for days :/
Anyway, you are right.
