### ISSUE TITLE
How ignore verification CN?

### ISSUE THREAD

**Issue by Cheban1996** [rustls/tokio-rustls#71]
I want ignore verification CN for my client beacause in my certs CN is not hosts

**Comment by cpu** [comment]
Rustls and tokio-rustls don't expose a toggle for disabling only server name validation. You would need to replace your Rustls config's server certificate verifier with your own that does all of the required checks except the name validation, or a dangerous version that does no verification at all. See the Rustls repo's [tlsclient-mio example](https://github.com/rustls/rustls/blob/a2c21fe0509f634431e72bffe8803fca1f892d56/examples/src/bin/tlsclient-mio.rs#L333-L394) as an example of accomplishing the latter.
