### ISSUE TITLE
Update to rustls 0.23.12?

### ISSUE THREAD

**Issue by lvkv** [rustls/tokio-rustls#81]
Hi team, it looks like `tokio-rustls` is currently pegged to `rustls` version 0.23.5. As of writing, the latest version is 0.23.12. Is bumping this possible? I typically don't use `rustls` directly and instead use it when re-exported through `tokio-rustls`, and I'd like to use some of the newer features like key consistency checks.

As always, feel free to push back if there's a good reason 🙂

**Comment by ctz** [comment]
So when the Cargo.toml in a crate says something like "0.23.5", that is a minimum. Any version 0.23.x for x >= 5 matches. So there is no work to do for this crate to be used with later versions, just run `cargo update` on your downstream repo.

**Comment by lvkv** [comment]
TIL, thanks!
