### ISSUE TITLE
Is there any buffer in server::TlsStream when reading?

### ISSUE THREAD

**Issue by leptonyu** [rustls/tokio-rustls#85]
I found that second packet of a new connection cannot read by server side, but when client send another packet 5secs later, server side can read normally.

**Comment by djc** [comment]
Yes, the rustls `ServerConnection` does contain an internal buffer, and if we've only received a partial TLS record we'll need to wait for the rest of the contents before we're able to decrypt it.

**Comment by leptonyu** [comment]
How to enforce a tls record? In this case, seems we need to let tlsstream generate a complete tls record, not a partial.

**Comment by djc** [comment]
Suggest you provide a complete minimal reproduction of your issue.

**Comment by cpu** [comment]
Closing this for now pending a reproducer.
